<!DOCTYPE html>
<html>
<head>
    <title><?= $title ?? 'SugarOA' ?></title>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta content="yes" name="apple-mobile-web-app-capable"/>
    <meta content="yes" name="apple-touch-fullscreen"/>
    <meta content="telephone=no" name="format-detection"/>
    <meta content="black" name="apple-mobile-web-app-status-bar-style">
    <link rel="stylesheet" href="/assets/styles/global.css">
    <link rel="stylesheet" href="/assets/styles/mini-icon.css">
    <link rel="stylesheet" href="/assets/easyui-1.5.2/themes/bootstrap/easyui.css">
    <link rel="stylesheet" href="/assets/easyui-1.5.2/themes/icon.css">
    <script src="/assets/easyui-1.5.2/jquery.min.js"></script>
    <script src="/assets/easyui-1.5.2/jquery.easyui.min.js"></script>
    <script src="/assets/easyui-1.5.2/locale/easyui-lang-zh_CN.js"></script>
    <script src="/assets/js/global.js"></script>

</head>
<body class="easyui-layout">
<?= $body ?>
</body>
</html>
