<div data-options="region:'center'" border="false" style="padding:5px">
    <div class="easyui-layout" data-options="fit:true">
        <div data-options="region:'center'" border="false">
            <div id="tgtb" style="padding:2px 0">
                <table cellpadding="0" cellspacing="0" style="width:100%">
                    <tr>
                        <td style="padding-left:2px">
                            <a href="##" class="easyui-linkbutton" iconCls="icon-reload" plain="true"
                               onclick="$('#tg').treegrid('reload');">刷新</a>
                            <a href="javascript:;" class="easyui-linkbutton" plain="true" iconCls="icon-folder-open"
                               onclick="$('#tg').treegrid('expandAll');">全部打开</a>
                            <a href="javascript:;" class="easyui-linkbutton" plain="true" iconCls="icon-folder-close"
                               onclick="$('#tg').treegrid('collapseAll');">全部关闭</a>
                            <input type="checkbox" id="auto_reload" value="1" checked=""> <label for="auto_reload">操作完成自动刷新</label>
                        </td>
                        <td style="text-align:right;padding-right:15px">
                        </td>
                    </tr>
                </table>
            </div>
            <table id="tg" toolbar="#tgtb" title="菜单管理" class="easyui-treegrid"
                   data-options="fit:true,tools:'#tg-tools',iconCls:'icon-menu'">
                <thead>
                <tr>
                    <th field="id" width="50">ID</th>
                    <th field="text" width="160">菜单名称</th>
                    <th field="href" width="200">菜单链接</th>
                    <th field="privileges" width="100" formatter="formatPrivileges">关联的权限</th>
                    <th field="sort" width="40">排序</th>
                    <th field="status" width="80" formatter="formatOperate">操作</th>
                </tr>
                </thead>
            </table>
            <!-- treegrid右上角工具栏 -->
            <div id="tg-tools">
                <a href="javascript:void(0)" class="icon-help" onclick="javascript:alert('权限管理帮助')"></a>
            </div>
        </div>
        <div data-options="region:'east',split:true" style="width:300px">
            <div id="pgtb" style="padding:2px">
                <table width="100%">
                    <tr>
                        <td>
                            <a href="javascript:;" class="easyui-linkbutton" iconCls="icon-add" plain="true" plain="true"
                               onclick="add();">添加菜单</a>
                        </td>
                        <td align="right">
                            <a id="pgtbSave" href="##" class="easyui-linkbutton" iconCls="icon-save"
                               onclick="save();">保存菜单</a>
                        </td>
                    </tr>
                </table>
            </div>
            <table id="pg" title="详细信息" toolbar="#pgtb" border="false" class="easyui-propertygrid" style="width:100%"
                   data-options="columns:columns,showGroup:true,scrollbarSize:0,url:'/menu/property',tools:'#pg-tools',iconCls:'icon-add'"></table>
            <!-- propertygrid右上角工具栏 -->
            <div id="pg-tools">
                <a href="javascript:void(0)" class="icon-help" onclick="javascript:alert('菜单详细信息帮助')"></a>
            </div>
        </div>
    </div>
</div>
<script>
    /**
     * 通过treegrid某行点击添加资源或操作时，会传入默认pid或resource值,但save()函数根据getChanges时获取不到
     * 所以遇到这种情况时，需要在save()中直接赋值,使用 var defaultValues的值作为判断依据
     */
    var defaultValues = {id: null, pid: null, resource: null};
    var menuObject = <?=$menus?>;
    var privilegeObject = <?=$privileges?>;

    var columns = [[
        {field: 'name', title: '名称', width: 30, sortable: true},
        {
            field: 'value', title: '值', width: 70, resizable: false,
            // 通过formatter处理一些值的显示问题
            formatter: function (value, row, index) {
                if (row.key == 'pid') {
                    return menuObject[value];
                } else if (row.key == 'privileges' && value) {
                    var privileges = value.toString().split(",");
                    var tmp = [];
                    for (var i = 0; i < privileges.length; i++) {
                        privilegeObject[privileges[i]] && tmp.push(privilegeObject[privileges[i]]);
                    }
                    return tmp.join(',');
                }
                return value;
            }
        }
    ]];

    $(function () {
        $('#tg').treegrid({
            url: '/menu/list',
            method: 'GET',
            idField: 'id',
            treeField: 'text',
            rownumbers: false,
            height: 'auto',
            fit: true,
            fitColumns: false,
            nowrap: true,
            onClickRow: function (row) {
                //console.log('onClickRow');
                /* 编辑菜单视图操作 */
                //console.log($('#pg').propertygrid('options'));
                //$('#pg').propertygrid('options').iconCls = 'icon-edit';
                $('#pg').propertygrid('load', {type: (row.resource ? 'resource' : 'group'), id: row.id});
                $('#pgtbSave').linkbutton({text: '保存修改', iconCls: 'icon-save'});
                defaultValues.id = row.id;
                defaultValues.pid = defaultValues.resource = null;
            },
            onLoadSuccess: function (data) {
                // 加载成功默认打开状态
                $('#tg').treegrid('expandAll');   //collapseAll
            },
            onLoadError: function () {
                alert('数据加载错误,请与管理员联系或稍候再试!');
            }
        });
    });

    function formatOperate(value, row, index) {
        var color = '';
        var text = '';
        var status = 0;
        if (row.status == 0) {
            color = "#008800";
            text = '启用';
            status = 1;
        } else {
            color = "#ff8800;";
            text = '禁用';
            status = 0;
        }
        var params = {
            status: "{id: " + row.id + ", status: " + status + "}",
            delete: "{id: " + row.id + ", deleted: 1}"
        };

        var operate = '<a href="##" onclick="javascript:save(' + params.status + ');" style="color:' + color + '">' + text + '</a>'
            + ' | <a href="##" onclick="javascript:save(' + params.delete + ');" style="color: #FF0000;">删除</a>';
        return operate;
    }

    function formatPrivileges(value, row, index) {
        if (row.privilegeArray) {
            var privileges = row.privilegeArray;
            var tmp = [];
            for (var i = 0; i < privileges.length; i++) {
                privilegeObject[privileges[i]] && tmp.push(privilegeObject[privileges[i]]);
            }
            return tmp.join(',');
        } else {
            return '';
        }
    }

    /* 增加菜单视图操作 */
    function add(){
        $('#pg').propertygrid('load',{});
        $('#pgtbSave').linkbutton({text: '保存新增'});
        defaultValues.id = null;
    }

    function save(params) {
        $('#pgtbSave').linkbutton('disable');
        if (!params) {
            params = {};

            //获取propertygrid加载时有设置默认值的值
            if (defaultValues.pid) params['pid'] = defaultValues.pid;

            var rows = $('#pg').propertygrid('getChanges');
            for (var i = 0; i < rows.length; i++) {
                params[rows[i].key] = rows[i].value;
            }

            if ($.isEmptyObject(params)) {
                $('#pgtbSave').linkbutton('enable');
                return false;
            }

            //如果是修改操作，要在params中传入id
            if (defaultValues.id) {
                params['id'] = defaultValues.id;
            }
            // defaultValues.id有值时视为update操作
            console.log(defaultValues);
        }

        $.post('/menu/save', params, function (data) {
            $('#pgtbSave').linkbutton('enable');

            if (data.error) {
                alert(data.message);
            } else {
                $.messager.show({
                    title:'提示',
                    msg:'保存成功！',
                    timeout:1000,
                    showType:'fade'
                });
                if (!params && !defaultValues.id) {
                    // 添加后可直接修改
                    defaultValues.id = data.id;
                    menuObject[data.id] = data.text;
                    console.log(defaultValues);
                }
                $('#auto_reload').is(":checked") && $('#tg').treegrid('reload');
            }
        }, 'json');
        return false;
    }
</script>
